server:
  port: 8082

spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      daultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 访问路径优先使用IP地址

